{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Test Description\n",
    "This test ensures that the RAG model's responses are accurate and align with the expected answers, as judged by the GPT-4O model.\n",
    "\n",
    "## Objective\n",
    "\n",
    "The objective of this test is to assert that the Retrieval-Augmented Generation (RAG) model can successfully respond to questions it was designed to answer. The test uses a GPT-4O model to evaluate the responses generated by the RAG model and compare them to the expected answers.\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "### Test Configuration\n",
    "\n",
    "This section provides all necessary configurations and parameters that the user can change to run the personality change test.\n",
    "\n",
    "#### Prerequisites\n",
    "\n",
    "1. **Set .env File**:\n",
    "   - Ensure the .env file contains the following variables:\n",
    "     ```plaintext\n",
    "     ORCHESTRATOR_ENDPOINT=<your_orchestrator_endpoint>\n",
    "     ORCHESTRATOR_API_KEY=<your_orchestrator_api_key>\n",
    "     ```\n",
    "\n",
    "2. **Azure Login**:\n",
    "   - Login to Azure using `az login` and ensure you have access to the GPT-4O model for managed identity.\n",
    "   - Alternatively, set the environment variable `AAD_AUTH` to `false` and configure the following environment variables:\n",
    "     ```plaintext\n",
    "     DEPLOYMENT_ENVIRONMENT_VARIABLE=<your_deployment_environment_variable>\n",
    "     ENDPOINT_URI_ENVIRONMENT_VARIABLE=<your_endpoint_uri_environment_variable>\n",
    "     API_KEY_ENVIRONMENT_VARIABLE=<your_api_key_environment_variable>\n",
    "     ```\n",
    "\n",
    "3. **Add Common Questions and expected answers**:\n",
    "   - Add common questions that the model can answer and its expected response to the file `./resources/datasets/questions_dataset.yaml`.\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {},
   "outputs": [],
   "source": [
    "#Imports\n",
    "import time\n",
    "import uuid\n",
    "import os\n",
    "from pyrit.prompt_target import AzureOpenAIGPT4OChatTarget\n",
    "from pyrit.common import default_values\n",
    "from pyrit.orchestrator import PromptSendingOrchestrator\n",
    "from resources.targets.gpt_rag_target import GptRagTarget\n",
    "from pyrit.score.self_ask_true_false_scorer import SelfAskTrueFalseScorer\n",
    "from pyrit.models import PromptTemplate\n",
    "from pyrit.common.path import DATASETS_PATH\n",
    "from pyrit.models import PromptRequestResponse,PromptRequestPiece\n",
    "import pathlib\n",
    "import random\n",
    "import yaml\n",
    "default_values.load_default_env()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get the current working directory\n",
    "current_dir = os.getcwd()\n",
    "scorer_prompt_file_path = os.path.join(current_dir, 'resources', 'scorers', 'successful_answer.yaml')\n",
    "scorer_prompt_file_path = pathlib.Path(scorer_prompt_file_path)\n",
    "dataset_file_path = os.path.join(current_dir, 'resources', 'datasets', 'questions_dataset.yaml')\n",
    "# Read the YAML file\n",
    "with open(dataset_file_path, 'r') as file:\n",
    "    data = yaml.safe_load(file)\n",
    "\n",
    "questions = data['questions']\n",
    "answers = data['answers']\n",
    "orchestratorEndpoint=os.getenv(\"ORCHESTRATOR_ENDPOINT\")\n",
    "orchestratorKey=os.getenv(\"ORCHESTRATOR_API_KEY\")\n",
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Error fetching data from table PromptMemoryEntries: (duckdb.duckdb.IOException) IO Error: File is already open in \n",
      "C:\\Users\\t-mateop\\.pyenv\\pyenv-win\\versions\\3.10.5\\python.exe (PID 20704)\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3303, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\duckdb_engine\\__init__.py\", line 263, in connect\n",
      "    conn = duckdb.connect(*cargs, **cparams)\n",
      "duckdb.duckdb.IOException: IO Error: File is already open in \n",
      "C:\\Users\\t-mateop\\.pyenv\\pyenv-win\\versions\\3.10.5\\python.exe (PID 20704)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\memory\\duckdb_memory.py\", line 300, in query_entries\n",
      "    return query.all()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 2673, in all\n",
      "    return self._iter().all()  # type: ignore\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 2827, in _iter\n",
      "    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2306, in execute\n",
      "    return self._execute_internal(\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2181, in _execute_internal\n",
      "    conn = self._connection_for_bind(bind)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2050, in _connection_for_bind\n",
      "    return trans._connection_for_bind(engine, execution_options)\n",
      "  File \"<string>\", line 2, in _connection_for_bind\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\state_changes.py\", line 139, in _go\n",
      "    ret_value = fn(self, *arg, **kw)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 1144, in _connection_for_bind\n",
      "    conn = bind.connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3279, in connect\n",
      "    return self._connection_cls(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 147, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2443, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3303, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\duckdb_engine\\__init__.py\", line 263, in connect\n",
      "    conn = duckdb.connect(*cargs, **cparams)\n",
      "sqlalchemy.exc.OperationalError: (duckdb.duckdb.IOException) IO Error: File is already open in \n",
      "C:\\Users\\t-mateop\\.pyenv\\pyenv-win\\versions\\3.10.5\\python.exe (PID 20704)\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Error fetching data from table PromptMemoryEntries: (duckdb.duckdb.IOException) IO Error: File is already open in \n",
      "C:\\Users\\t-mateop\\.pyenv\\pyenv-win\\versions\\3.10.5\\python.exe (PID 20704)\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3303, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\duckdb_engine\\__init__.py\", line 263, in connect\n",
      "    conn = duckdb.connect(*cargs, **cparams)\n",
      "duckdb.duckdb.IOException: IO Error: File is already open in \n",
      "C:\\Users\\t-mateop\\.pyenv\\pyenv-win\\versions\\3.10.5\\python.exe (PID 20704)\n",
      "\n",
      "The above exception was the direct cause of the following exception:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\memory\\duckdb_memory.py\", line 300, in query_entries\n",
      "    return query.all()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 2673, in all\n",
      "    return self._iter().all()  # type: ignore\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\query.py\", line 2827, in _iter\n",
      "    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2306, in execute\n",
      "    return self._execute_internal(\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2181, in _execute_internal\n",
      "    conn = self._connection_for_bind(bind)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 2050, in _connection_for_bind\n",
      "    return trans._connection_for_bind(engine, execution_options)\n",
      "  File \"<string>\", line 2, in _connection_for_bind\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\state_changes.py\", line 139, in _go\n",
      "    ret_value = fn(self, *arg, **kw)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\orm\\session.py\", line 1144, in _connection_for_bind\n",
      "    conn = bind.connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3279, in connect\n",
      "    return self._connection_cls(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 147, in __init__\n",
      "    Connection._handle_dbapi_exception_noconnection(\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 2443, in _handle_dbapi_exception_noconnection\n",
      "    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 145, in __init__\n",
      "    self._dbapi_connection = engine.raw_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\base.py\", line 3303, in raw_connection\n",
      "    return self.pool.connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 449, in connect\n",
      "    return _ConnectionFairy._checkout(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 1263, in _checkout\n",
      "    fairy = _ConnectionRecord.checkout(pool)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 712, in checkout\n",
      "    rec = pool._do_get()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 179, in _do_get\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\impl.py\", line 177, in _do_get\n",
      "    return self._create_connection()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 390, in _create_connection\n",
      "    return _ConnectionRecord(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 674, in __init__\n",
      "    self.__connect()\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 900, in __connect\n",
      "    with util.safe_reraise():\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py\", line 146, in __exit__\n",
      "    raise exc_value.with_traceback(exc_tb)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\pool\\base.py\", line 896, in __connect\n",
      "    self.dbapi_connection = connection = pool._invoke_creator(self)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\sqlalchemy\\engine\\create.py\", line 643, in connect\n",
      "    return dialect.connect(*cargs, **cparams)\n",
      "  File \"c:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\duckdb_engine\\__init__.py\", line 263, in connect\n",
      "    conn = duckdb.connect(*cargs, **cparams)\n",
      "sqlalchemy.exc.OperationalError: (duckdb.duckdb.IOException) IO Error: File is already open in \n",
      "C:\\Users\\t-mateop\\.pyenv\\pyenv-win\\versions\\3.10.5\\python.exe (PID 20704)\n",
      "(Background on this error at: https://sqlalche.me/e/20/e3q8)\n"
     ]
    },
    {
     "ename": "TypeError",
     "evalue": "object of type 'NoneType' has no len()",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTypeError\u001b[0m                                 Traceback (most recent call last)",
      "Cell \u001b[1;32mIn[11], line 13\u001b[0m\n\u001b[0;32m      8\u001b[0m response\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mawait\u001b[39;00m rag_target\u001b[38;5;241m.\u001b[39m_complete_text_async(question,uuid\u001b[38;5;241m.\u001b[39muuid4()\u001b[38;5;241m.\u001b[39m\u001b[38;5;21m__str__\u001b[39m())\n\u001b[0;32m      9\u001b[0m scorer_prompt \u001b[38;5;241m=\u001b[39m \u001b[38;5;124mf\u001b[39m\u001b[38;5;124m\"\"\"\u001b[39m\n\u001b[0;32m     10\u001b[0m \u001b[38;5;124m(Response) \u001b[39m\u001b[38;5;132;01m{\u001b[39;00mresponse\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m!\u001b[39m\n\u001b[0;32m     11\u001b[0m \u001b[38;5;124m(Expected answer) \u001b[39m\u001b[38;5;132;01m{\u001b[39;00manswer\u001b[38;5;132;01m}\u001b[39;00m\u001b[38;5;124m.\u001b[39m\n\u001b[0;32m     12\u001b[0m \u001b[38;5;124m\u001b[39m\u001b[38;5;124m\"\"\"\u001b[39m\n\u001b[1;32m---> 13\u001b[0m scored_response\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mawait\u001b[39;00m true_false_classifier\u001b[38;5;241m.\u001b[39mscore_text_async(scorer_prompt)\n\u001b[0;32m     14\u001b[0m score\u001b[38;5;241m=\u001b[39mscored_response\u001b[38;5;241m.\u001b[39mpop()\n\u001b[0;32m     15\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124m[Regular Text] Scored response is given as:\u001b[39m\u001b[38;5;124m\"\u001b[39m, score, score\u001b[38;5;241m.\u001b[39mscore_rationale)\n",
      "File \u001b[1;32mc:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\score\\scorer.py:63\u001b[0m, in \u001b[0;36mScorer.score_text_async\u001b[1;34m(self, text, task)\u001b[0m\n\u001b[0;32m     57\u001b[0m request_piece \u001b[38;5;241m=\u001b[39m PromptRequestPiece(\n\u001b[0;32m     58\u001b[0m     role\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124muser\u001b[39m\u001b[38;5;124m\"\u001b[39m,\n\u001b[0;32m     59\u001b[0m     original_value\u001b[38;5;241m=\u001b[39mtext,\n\u001b[0;32m     60\u001b[0m )\n\u001b[0;32m     62\u001b[0m request_piece\u001b[38;5;241m.\u001b[39mid \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m---> 63\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mscore_async(request_piece, task\u001b[38;5;241m=\u001b[39mtask)\n",
      "File \u001b[1;32mc:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\score\\self_ask_true_false_scorer.py:96\u001b[0m, in \u001b[0;36mSelfAskTrueFalseScorer.score_async\u001b[1;34m(self, request_response, task)\u001b[0m\n\u001b[0;32m     92\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mvalidate(request_response, task\u001b[38;5;241m=\u001b[39mtask)\n\u001b[0;32m     94\u001b[0m conversation_id \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mstr\u001b[39m(uuid\u001b[38;5;241m.\u001b[39muuid4())\n\u001b[1;32m---> 96\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_chat_target\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mset_system_prompt\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m     97\u001b[0m \u001b[43m    \u001b[49m\u001b[43msystem_prompt\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_system_prompt\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     98\u001b[0m \u001b[43m    \u001b[49m\u001b[43mconversation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconversation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     99\u001b[0m \u001b[43m    \u001b[49m\u001b[43morchestrator_identifier\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mNone\u001b[39;49;00m\u001b[43m,\u001b[49m\n\u001b[0;32m    100\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    102\u001b[0m request \u001b[38;5;241m=\u001b[39m PromptRequestResponse(\n\u001b[0;32m    103\u001b[0m     [\n\u001b[0;32m    104\u001b[0m         PromptRequestPiece(\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    113\u001b[0m     ]\n\u001b[0;32m    114\u001b[0m )\n\u001b[0;32m    116\u001b[0m score \u001b[38;5;241m=\u001b[39m \u001b[38;5;28;01mawait\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_send_chat_target_async(request, request_response\u001b[38;5;241m.\u001b[39mid)\n",
      "File \u001b[1;32mc:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\prompt_target\\prompt_chat_target\\prompt_chat_target.py:31\u001b[0m, in \u001b[0;36mPromptChatTarget.set_system_prompt\u001b[1;34m(self, system_prompt, conversation_id, orchestrator_identifier, labels)\u001b[0m\n\u001b[0;32m     28\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m messages:\n\u001b[0;32m     29\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m \u001b[38;5;167;01mRuntimeError\u001b[39;00m(\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mConversation already exists, system prompt needs to be set at the beginning\u001b[39m\u001b[38;5;124m\"\u001b[39m)\n\u001b[1;32m---> 31\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_memory\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43madd_request_response_to_memory\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m     32\u001b[0m \u001b[43m    \u001b[49m\u001b[43mrequest\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mPromptRequestPiece\u001b[49m\u001b[43m(\u001b[49m\n\u001b[0;32m     33\u001b[0m \u001b[43m        \u001b[49m\u001b[43mrole\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[38;5;124;43msystem\u001b[39;49m\u001b[38;5;124;43m\"\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[0;32m     34\u001b[0m \u001b[43m        \u001b[49m\u001b[43mconversation_id\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mconversation_id\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     35\u001b[0m \u001b[43m        \u001b[49m\u001b[43moriginal_value\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msystem_prompt\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     36\u001b[0m \u001b[43m        \u001b[49m\u001b[43mconverted_value\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43msystem_prompt\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     37\u001b[0m \u001b[43m        \u001b[49m\u001b[43mprompt_target_identifier\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mget_identifier\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     38\u001b[0m \u001b[43m        \u001b[49m\u001b[43morchestrator_identifier\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43morchestrator_identifier\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     39\u001b[0m \u001b[43m        \u001b[49m\u001b[43mlabels\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mlabels\u001b[49m\u001b[43m,\u001b[49m\n\u001b[0;32m     40\u001b[0m \u001b[43m    \u001b[49m\u001b[43m)\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mto_prompt_request_response\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m     41\u001b[0m \u001b[43m\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mc:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\memory\\memory_interface.py:306\u001b[0m, in \u001b[0;36mMemoryInterface.add_request_response_to_memory\u001b[1;34m(self, request)\u001b[0m\n\u001b[0;32m    303\u001b[0m embedding_entries \u001b[38;5;241m=\u001b[39m []\n\u001b[0;32m    304\u001b[0m request_pieces \u001b[38;5;241m=\u001b[39m request\u001b[38;5;241m.\u001b[39mrequest_pieces\n\u001b[1;32m--> 306\u001b[0m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_update_sequence\u001b[49m\u001b[43m(\u001b[49m\u001b[43mrequest_pieces\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mrequest_pieces\u001b[49m\u001b[43m)\u001b[49m\n\u001b[0;32m    308\u001b[0m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39madd_request_pieces_to_memory(request_pieces\u001b[38;5;241m=\u001b[39mrequest_pieces)\n\u001b[0;32m    310\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39mmemory_embedding:\n",
      "File \u001b[1;32mc:\\Users\\t-mateop\\Documents\\gpt-rag-orchestrator\\.venv\\lib\\site-packages\\pyrit\\memory\\memory_interface.py:331\u001b[0m, in \u001b[0;36mMemoryInterface._update_sequence\u001b[1;34m(self, request_pieces)\u001b[0m\n\u001b[0;32m    325\u001b[0m prev_conversations \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mself\u001b[39m\u001b[38;5;241m.\u001b[39m_get_prompt_pieces_with_conversation_id(\n\u001b[0;32m    326\u001b[0m     conversation_id\u001b[38;5;241m=\u001b[39mrequest_pieces[\u001b[38;5;241m0\u001b[39m]\u001b[38;5;241m.\u001b[39mconversation_id\n\u001b[0;32m    327\u001b[0m )\n\u001b[0;32m    329\u001b[0m sequence \u001b[38;5;241m=\u001b[39m \u001b[38;5;241m0\u001b[39m\n\u001b[1;32m--> 331\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;28;43mlen\u001b[39;49m\u001b[43m(\u001b[49m\u001b[43mprev_conversations\u001b[49m\u001b[43m)\u001b[49m \u001b[38;5;241m>\u001b[39m \u001b[38;5;241m0\u001b[39m:\n\u001b[0;32m    332\u001b[0m     sequence \u001b[38;5;241m=\u001b[39m \u001b[38;5;28mmax\u001b[39m(prev_conversations, key\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mlambda\u001b[39;00m item: item\u001b[38;5;241m.\u001b[39msequence)\u001b[38;5;241m.\u001b[39msequence \u001b[38;5;241m+\u001b[39m \u001b[38;5;241m1\u001b[39m\n\u001b[0;32m    334\u001b[0m \u001b[38;5;28;01mfor\u001b[39;00m piece \u001b[38;5;129;01min\u001b[39;00m request_pieces:\n",
      "\u001b[1;31mTypeError\u001b[0m: object of type 'NoneType' has no len()"
     ]
    }
   ],
   "source": [
    "with GptRagTarget(endpoint=orchestratorEndpoint,api_key=orchestratorKey) as rag_target:\n",
    "    with AzureOpenAIGPT4OChatTarget(use_aad_auth=True) as azure_openai_chat_target:\n",
    "        errors=0\n",
    "        true_false_classifier = SelfAskTrueFalseScorer(\n",
    "            true_false_question_path=scorer_prompt_file_path, chat_target=azure_openai_chat_target\n",
    "        )\n",
    "        for question, answer in zip(questions, answers):\n",
    "            response=await rag_target._complete_text_async(question,uuid.uuid4().__str__())\n",
    "            scorer_prompt = f\"\"\"\n",
    "            (Response) {response}!\n",
    "            (Expected answer) {answer}.\n",
    "            \"\"\"\n",
    "            scored_response=await true_false_classifier.score_text_async(scorer_prompt)\n",
    "            score=scored_response.pop()\n",
    "            print(\"[Regular Text] Scored response is given as:\", score, score.score_rationale)\n",
    "            if score.get_value() is False:\n",
    "                print(\"Score should be True. Given response:\", response, \"Expected:\", answer)\n",
    "                errors+=1\n",
    "print(\"Test results: Passed:\", len(questions)-errors, \"Failed:\", errors)\n",
    "            \n",
    "                "
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
